version: "3"

services:
  test-db:
    image: postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: pass123
  test-redis:
    image: redis
    restart: always
    ports:
      - "6380:6379"
  
