name: cd

on:
  push:
    branches:
      - master

jobs:
  buildpushdocker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to SW Container Registry
        uses: docker/login-action@v1
        with:
          registry: rg.fr-par.scw.cloud/welcomemap
          username: nologin
          password: ${{ secrets.SW_HUB_PW }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: rg.fr-par.scw.cloud/woozir/woozir-core:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
