name: cd

on:
  push:
    branches:
      - main

jobs:
  teste2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: npm i --legacy-peer-deps
      - name: Run unit tests
        run: npm test
      - name: Run tests
        run: npm run test:e2e

  buildpushdocker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to SW Container Registry
        uses: docker/login-action@v1
        with:
          registry: rg.fr-par.scw.cloud/welcome-map
          username: nologin
          password: ${{ secrets.SW_HUB_PW }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: rg.fr-par.scw.cloud/welcome-map/welcome-core:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
